micronaut:
  application:
    name: gadget-inventory
  security:
    enabled: false


jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

datasources:
  default:
    enabled: true
    url: jdbc:postgresql://localhost:5432/gadgetdb
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
